import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import image1 from "../images/gymname.png"
import Image from 'next/image';
import Rfooter from "../components/ui/footer"





const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <header>This is our header</header>
        {children}
              
        <footer
          className="block"
          style={{ position: 'relative', top:0, bottom: 0, left: 0, right: 0 }}
        >
          <Rfooter />
        </footer>     </body>
    
    </html>
  )
}
